global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'co2_leakage_detection'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting_rules:
  groups:
    - name: ml_model_alerts
      rules:
        - alert: HighModelLatency
          expr: prediction_latency_seconds > 0.5
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High model prediction latency"
            description: "Model prediction latency is above 500ms for 5 minutes"

        - alert: LowModelAccuracy
          expr: sum(prediction_total{result="correct"}) / sum(prediction_total) < 0.9
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: "Model accuracy degradation"
            description: "Model accuracy has dropped below 90% for 15 minutes"

        - alert: FeatureDrift
          expr: feature_drift > 0.1
          for: 30m
          labels:
            severity: warning
          annotations:
            summary: "Feature drift detected"
            description: "Significant feature drift detected in the model inputs"